version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

    commands:
      - apt-get update
      - apt-get install -y make

  pre_build:
    commands:
      - echo "Pre-build steps go here"

  build:
    commands:
      - mvn clean install -DskipTests
      - pwd
  
#   artifacts:
#     files:
#       - /OpenMetadata/openmetadata-dist/target/*.tar.gz
#     name: mytarfile 
  
#   artifacts:
#   files:
#     - /home/runner/work/OpenMetadata/OpenMetadata/openmetadata-dist/target/*.tar.gz
#    name: myname-$AWS_REGION
#   discard-paths: yes

  post_build:
    commands:
      - echo "Post-build steps go here"
      - aws s3 cp /home/runner/work/OpenMetadata/OpenMetadata/openmetadata-dist/target/*.tar.gz s3://myartifactbucket-1/openmetadata-binary/

# version: 0.2

# phases:
#   pre_build:
#     commands:
#       # Install and configure AWS CLI
#       - yum update -y
#       - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
#       - unzip awscliv2.zip
#       - ./aws/install
# #       - apt-get install -y awscli

#   build:
#     commands:
#       # Build the Docker image
#       - yum install -y docker
#       - systemctl enable docker.service
#       - systemctl start docker.service

#       - docker pull ubuntu:latest
#       # Authenticate Docker with ECR
#       - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s6h3m1v6
# #       - $(aws ecr get-login --no-include-email --region your-aws-region)
#       # Tag the Docker image
#       - docker tag ubuntu:latest public.ecr.aws/s6h3m1v6/ubuntu:latest

#   post_build:
#     commands:
# #       docker tag ubuntu:latest public.ecr.aws/s6h3m1v6/ubuntu:latest
#       # Push the Docker image to ECR
#       - docker push public.ecr.aws/s6h3m1v6/ubuntu:latest
# #       - docker push your-ecr-repo-url/my_image:tag

